---
all:
  children:
    marzban:
      children:
        marzban_main:
          hosts:
            main:
              ansible_host: <your-panel-ip>
              ansible_port: <your-panel-port>
              marzban_roles:
                - panel
        marzban_nodes:
          hosts:
            node1:
              ansible_host: <node-1-ip>
              ansible_port: <node-1-port>
              marzban_roles:
                - node
            node2:
              ansible_host: <node-2-ip>
              ansible_port: <node-2-port>
              marzban_roles:
                - node
