---

- name: "Marzban | Prepare"
  include_tasks: prepare.yml

- name: "Marzban | Warp"
  include_tasks: warp.yml
  tags: warp
  when: marzban_warp

- name: "Marzban | Configure marzban instance tasks"
  include_tasks: "conf/{{ role }}.yml"
  loop: "{{ marzban_roles }}"
  loop_control:
    loop_var: role
  tags:
    - configure


- name: "Marzban | Add nodes"
  include_tasks: add-node.yml
  when:
    - marzban_nodes_group_name in groups

- name: "Marzban | Post-deploy"
  include_tasks: post-deploy.yml
