---

# Main domain for the Marzban panel/reality
marzban_domain: "your-domain.example"

# Subdomain for Marzban control panel access (Full path: {{ panel_path }}.{{ marzban_domain }})
marzban_panel_uri: "panel.{{ marzban_domain }}"

# SNI for traffic masking
marzban_sni: "masking-domain.example"

# Login credentials for panel access
marzban_panel_login: "admin"
# Password must not contain symbols like ^$
marzban_panel_password: "ultradmin"

# Port for VLESS Reality TCP connections
marzban_vless_tcp_reality_port: "12000"

# Ports for communication with the Marzban node:
# - First port: service port
# - Second port: API port for xray-core
marzban_api_ports:
  - "62050"
  - "62051"

# Use Cloudflare WARP for outbound traffic (true/false)
marzban_warp: true

# Enable API documentation (available at /docs and /redoc)
marzban_docs: true

# Use MySQL(maria-db) instance instead of SQLite (true/false)
marzban_mysql_instance: true

# Enable automatic backup (true/false)
marzban_backup: true
# Backup schedule (cron format)
marzban_backup_cron: { minute: "0", hour: "3", day: "1,10,20", month: "*", weekday: "*" }

# Telegram bot token for backup notifications (leave empty if not needed)
marzban_backup_telegram_bot_token: "token-bot-bkp"
# Telegram chat ID for backup notifications (auto-detected if empty; initiate chat with the bot first)
marzban_backup_telegram_chat_id: "your-tg-id"

# Use custom template for subscription page  for placing various clients regarding different operating systems and tutorials related to them
marzban_custom_subscription_template: true

# DNS servers list
marzban_dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
  - "1.1.1.1"
  - "1.0.0.1"

# Direct domains list (traffic bypasses the tunnel)
marzban_direct_domains:
  - "full:cp.cloudflare.com"
  - "domain:msftconnecttest.com"
  - "domain:msftncsi.com"
  - "domain:connectivitycheck.gstatic.com"
  - "domain:captive.apple.com"
  - "full:detectportal.firefox.com"
  - "domain:networkcheck.kde.org"
  - "domain:gosuslugi.ru"
  - "domain:vk.com"
  - "domain:vk-portal.net"
  - "domain:vkuseraudio.com"
  - "domain:ozon.ru"
  - "domain:userapi.com"
  - "domain:mycdn.me"
  - "domain:mradx.net"
  - "domain:mail.ru"
  - "domain:okcdn.ru"
  - "domain:dzen.ru"
  - "domain:dzeninfra.ru"
  - "domain:consentmanager.net"
  - "domain:yandex.net"
  - "domain:yandex.ru"
  - "domain:imgsmail.ru"
  - "domain:yastatic.net"
  - "domain:yadro.ru"

# Cloudflare WARP traffic filtering settings
marzban_warp_domains:
  - "geosite:openai"
  - "domain:ipinfo.io"
  - "domain:iplocation.net"
  - "domain:spotify.com"
  - "domain:linkedin.com"

# Panel logging level
marzban_log_level: "warning"

# Time zone configuration
common_timezone: "Europe/Moscow"

# Install custom Xanmod kernel with BBR3 support (true/false)
common_xanmod_kernel: true

# Additional packages to install on nodes
common_additional_packages:
  - "vnstat"
  - "git"

### Automatic Certificate Management ###
# Enable automatic certificate generation and renewal (true/false)
marzban_auto_cert: true

# Certificate challenge method: "http" or "dns"
# http: Uses HTTP-01 challenge (for single domain)
# dns: Uses DNS-01 challenge (supports wildcards, requires DNS provider API)
# DNS provider settings (for DNS-01 challenge)
marzban_cert_challenge_method: "dns" # ["http, only if we can proof"]

# Email for Let's Encrypt registration
marzban_cert_email: "<email for acme registration>"

# Staging environment (true for testing, false for production)
marzban_cert_staging: false

# Certificate domains to obtain
marzban_cert_domains:
  - "{{ marzban_domain }}"
  - "*.{{ marzban_domain }}"

marzban_cert_dns_provider: "cloudns"
marzban_cert_dns_credentials:
  cloudns_auth_id: "<cloudns-auth-id>"
  cloudns_auth_password: "<cloudns-auth-pwd>"
# dns_cloudns_sub_auth_id

# marzban_cert_dns_provider: [cloudflare, amazon, route53, digital_ocean]
# > dns_cloudflare_api_token | [dns_cloudflare_email, dns_cloudflare_api_key]
# > dns_digitalocean_token
# > [dns_route53_access_key_id, dns_route53_secret_access_key]
# Certificate renewal settings
marzban_cert_renewal_interval: "43200"  # 12 hours


### SSL Configuration ###
# Certificate and key names must be in the format: {{ some_cool_name }}.cert and {{ some_cool_name }}.key
# Certificates will be used in marzban_ssl_certfile and marzban_ssl_keyfile
# Certificates should cover both the domain {{ marzban_domain }} and its wildcard *.{{ marzban_domain }}
# fallback option
vault_ssl_certs:
  your-domain.example.cert: |
    <fullchain.pem>
  your-domain.example.key: |
    <privkey.pem>
